[package]
name = "vesting"
version = "1.0.0"
authors = ["Taiwo Triumphant"]
upgrade_policy="compatible"

[addresses]
blockchain = "0x99052ed7ce92d86ab32ae0c8de30fe5dcec274bb34056a938c34f3ac90aadc3a"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"
